SCENARIOS = {
    "fateful-baseball": {
        "title": "The Baseball Detour",
        "description": "A harmless outing can spiral through bad influence and risk into fatal outcomes.",
        "nfa": {
            "states": [
                "Alive",
                "BaseballGame",
                "MeetStranger",
                "Infatuated",
                "BadInfluence",
                "HospitalVisit",
                "RecklessMoment",
                "CloseCall",
                "FinalChoice",
                "DEATH",
            ],
            "start": "Alive",
            "accepting": {"DEATH"},
            "state_details": {
                "Alive": "Baseline state. You are safe, stable, and not currently escalating risk.",
                "BaseballGame": "A social detour. A neutral choice that creates new chance encounters.",
                "MeetStranger": "A branching social moment. You can disconnect safely or get pulled deeper.",
                "Infatuated": "Emotional tunnel vision begins. Judgment can drift without explicit decisions.",
                "BadInfluence": "Risky external pressure. Multiple bad outcomes now become reachable quickly.",
                "HospitalVisit": "A warning state after harm. You can still recover or worsen the trajectory.",
                "RecklessMoment": "High-volatility behavior. A single decision can lock in irreversible consequences.",
                "CloseCall": "You survive, but the lesson is not guaranteed. This can reset or relapse.",
                "FinalChoice": "Terminal decision boundary. Remaining paths are effectively fatal.",
                "DEATH": "Accepting state. Any path ending here satisfies the fatal language condition.",
            },
            "transitions": [
                ("Alive", "Go to baseball game", "BaseballGame"),
                ("Alive", "Stay home", "Alive"),
                ("BaseballGame", "Meet someone", "MeetStranger"),
                ("BaseballGame", "ε", "Alive"),
                ("MeetStranger", "Exchange numbers", "Infatuated"),
                ("MeetStranger", "Walk away", "Alive"),
                ("Infatuated", "ε", "BadInfluence"),
                ("Infatuated", "Keep distance", "Alive"),
                ("BadInfluence", "Follow their lead", "RecklessMoment"),
                ("BadInfluence", "Late night drive", "HospitalVisit"),
                ("BadInfluence", "Ignore warning signs", "RecklessMoment"),
                ("HospitalVisit", "ε", "CloseCall"),
                ("HospitalVisit", "Leave AMA", "RecklessMoment"),
                ("RecklessMoment", "Point of no return", "FinalChoice"),
                ("RecklessMoment", "Survive by luck", "CloseCall"),
                ("CloseCall", "Learn nothing", "BadInfluence"),
                ("CloseCall", "Change course", "Alive"),
                ("FinalChoice", "Accept the risk", "DEATH"),
                ("FinalChoice", "ε", "DEATH"),
            ],
        },
    },
    "after-party-drive": {
        "title": "The After-Party Drive",
        "description": "Trying to keep up can loop through risky behavior; some exits are safe, others fatal.",
        "nfa": {
            "states": [
                "Alive",
                "LateParty",
                "PeerPressure",
                "ImpairedDrive",
                "Checkpoint",
                "CrashRisk",
                "Recovery",
                "FinalChoice",
                "DEATH",
            ],
            "start": "Alive",
            "accepting": {"DEATH"},
            "state_details": {
                "Alive": "Stable baseline. Low-risk behavior keeps the automaton in a safe loop.",
                "LateParty": "Environment shift. Social pressure and fatigue increase poor-decision probability.",
                "PeerPressure": "External influence state. You can choose safety or slide into impairment.",
                "ImpairedDrive": "Cognitive and reaction risk spike. Mistakes compound quickly from here.",
                "Checkpoint": "Intervention point. Calm compliance can de-escalate, panic can escalate.",
                "CrashRisk": "Acute danger state. Outcomes can include near miss or direct progression to fatality.",
                "Recovery": "Protective branch. Reflection can return to safety, repetition loops back to risk.",
                "FinalChoice": "Last-risk boundary before acceptance. Choices here represent irreversible exposure.",
                "DEATH": "Accepting state for fatal trajectories in this scenario.",
            },
            "transitions": [
                ("Alive", "Go out late", "LateParty"),
                ("Alive", "Stay home", "Alive"),
                ("LateParty", "Follow the crowd", "PeerPressure"),
                ("LateParty", "Leave early", "Alive"),
                ("PeerPressure", "ε", "ImpairedDrive"),
                ("PeerPressure", "Call a ride", "Recovery"),
                ("ImpairedDrive", "Speed", "CrashRisk"),
                ("ImpairedDrive", "Take back roads", "Checkpoint"),
                ("Checkpoint", "Panic", "CrashRisk"),
                ("Checkpoint", "Cooperate", "Recovery"),
                ("CrashRisk", "Lose control", "FinalChoice"),
                ("CrashRisk", "Near miss", "Recovery"),
                ("Recovery", "Learn and change", "Alive"),
                ("Recovery", "Repeat pattern", "PeerPressure"),
                ("FinalChoice", "Accept the risk", "DEATH"),
                ("FinalChoice", "ε", "DEATH"),
            ],
        },
    },
    "road-rage-spiral": {
        "title": "The Road-Rage Spiral",
        "description": "A small traffic conflict can escalate through pride and impulsive choices into irreversible outcomes.",
        "nfa": {
            "states": [
                "Alive",
                "TrafficDelay",
                "Provoked",
                "ChaseImpulse",
                "AggressiveManeuver",
                "NearMiss",
                "PoliceStop",
                "Recovery",
                "FinalChoice",
                "DEATH",
            ],
            "start": "Alive",
            "accepting": {"DEATH"},
            "state_details": {
                "Alive": "Neutral baseline driving state with no active conflict.",
                "TrafficDelay": "Frustration trigger. Delay itself is harmless but primes emotional escalation.",
                "Provoked": "Emotional ignition state. Ego and anger make impulsive branches more likely.",
                "ChaseImpulse": "Retaliatory mindset. You are now prioritizing reaction over safety.",
                "AggressiveManeuver": "Dangerous tactical driving. Error tolerance is minimal.",
                "NearMiss": "Immediate scare state. You can learn and recover or re-enter escalation.",
                "PoliceStop": "External intervention. Compliance can de-escalate; panic can worsen outcomes.",
                "Recovery": "Decompression branch. Behavior can reset to safe driving or relapse to provocation.",
                "FinalChoice": "Critical threshold where one more risk decision can become fatal.",
                "DEATH": "Accepting fatal state for the road-rage language.",
            },
            "transitions": [
                ("Alive", "Drive during rush hour", "TrafficDelay"),
                ("Alive", "Stay calm", "Alive"),
                ("TrafficDelay", "Get cut off", "Provoked"),
                ("TrafficDelay", "Let it go", "Alive"),
                ("Provoked", "Tailgate", "ChaseImpulse"),
                ("Provoked", "Breathe and reset", "Recovery"),
                ("Provoked", "ε", "ChaseImpulse"),
                ("ChaseImpulse", "Weave through lanes", "AggressiveManeuver"),
                ("ChaseImpulse", "Back off", "NearMiss"),
                ("AggressiveManeuver", "Run red light", "FinalChoice"),
                ("AggressiveManeuver", "Get pulled over", "PoliceStop"),
                ("NearMiss", "Learn from scare", "Recovery"),
                ("NearMiss", "Escalate again", "Provoked"),
                ("PoliceStop", "Cooperate", "Recovery"),
                ("PoliceStop", "Drive off in panic", "FinalChoice"),
                ("Recovery", "Change habits", "Alive"),
                ("Recovery", "Hold a grudge", "Provoked"),
                ("FinalChoice", "Accept the risk", "DEATH"),
                ("FinalChoice", "ε", "DEATH"),
            ],
        },
    },
}

DEFAULT_SCENARIO_KEY = "fateful-baseball"
